### **`Problem-1:`** Write a Python function that takes a list and returns a new list with unique elements of the first list.

**Exercise 1:**

Input:

```bash
[1,2,3,3,3,3,4,5]
```

Output:

```bash
[1, 2, 3, 4, 5]
```

In [ ]:
# def unique(n):
#   sets = set()
#   for i in n:
#     sets.add(i)
#   return list(sets)
# lst = [1,2,3,3,3,3,4,5]
# print(unique(lst))

def unique(n):
  res = []

  for i in n:
    if i not in res:
      res.append(i)
  return res
lst = [1,2,3,3,3,3,4,5]
print(unique(lst))

[1, 2, 3, 4, 5]

### **`Problem-2:`** Write a Python function that accepts a hyphen-separated sequence of words as parameter and returns the words in a hyphen-separated sequence after sorting them alphabetically.

**Example 1:**

Input:
```bash
green-red-yellow-black-white
```

Output:
```bash
black-green-red-white-yellow
```

In [ ]:
def sortedn (n):
  spl = n.split("-")
  lst = sorted(spl)
  res = "-".join(lst)
  return res
str = "green-red-yellow-black-white"
s = sortedn(str)
print(s)

black-green-red-white-yellow

### **`Problem 3:`** Write a Python function that accepts a string and calculate the number of upper case letters and lower case letters.

```
Sample String : 'CampusX is an Online Mentorship Program fOr EnginEering studentS.'
Expected Output :
No. of Upper case characters :  9
No. of Lower case Characters :  47
```

In [ ]:
def counts(s):
  countsmall = 0
  countcap = 0
  for i in s:
    if i.islower():
      countsmall += 1
    elif i.isupper():
      countcap += 1
    else:
      pass
  return countsmall ,countcap
String = 'CampusX is an Online Mentorship Program fOr EnginEering studentS.'
x,y = counts(String)
print("No. of Upper case characters:",y)
print("No. of Lowrer case characters:" , x)

No. of Upper case characters: 9
No. of Lowrer case characters: 47

### **`Problem 4:`** Write a Python program to print the even numbers from a given list.
```
Sample List : [1, 2, 3, 4, 5, 6, 7, 8, 9]
Expected Result : [2, 4, 6, 8]
```

In [ ]:
def is_even(l):
  lst2 = []
  for i in l:
    if (i % 2 == 0):
      lst2.append(i)
    else:
      pass
  return lst2
List = [1, 2, 3, 4, 5, 6, 7, 8, 9]
is_even(List)

[2, 4, 6, 8]

### **`Problem 5:`** Write a Python function to check whether a number is perfect or not.

A Perfect number is a number that is half the sum of all of its positive divisors (including itself).

Example :

```
The first perfect number is 6, because 1, 2, and 3 are its proper positive divisors, and 1 + 2 + 3 = 6.
Equivalently, the number 6 is equal to half the sum of all its positive divisors: ( 1 + 2 + 3 + 6 ) / 2 = 6.

The next perfect number is 28 = 1 + 2 + 4 + 7 + 14. This is followed by the perfect numbers 496 and 8128.
```

In [10]:

# def perfect_num(num):
#   lst =[]
#   count = 0
#   for i in range(1,(num//2)+1):
#     if(num % i == 0):
#       lst.append(i)
#   for i in lst:
#     count = count + i
#   if ( (count + num) //2 == num):
#     return "Perfect Number"
#   else:
#     return "Not a perfect number"
# n = 6
# perfect_num(n)

def perfect_num(num):
  sum = 0
  for i in range(1,num//2 +1):
    if(n%i == 0):
      sum = sum + i
    else:
      pass
  if(sum == num):
    return True
  else:
    return False
n = 496
perfect_num(n)

True

### **`Problem-6:`** Write a Python function to concatenate any no of dictionaries to create a new one.

```
Sample Dictionary :
dic1={1:10, 2:20}
dic2={3:30, 4:40}
dic3={5:50,6:60}
Expected Result : {1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}
```

In [20]:
def concat(*dic):
  dic1 = {}
  for i in dic:
    dic1.update(i)
  return dic1
d = {"name": "sunil kumar", "age": 23}
n = {"Name": "piyush" , "Age" : 23}
x = concat(d,n)
print(x)

{'name': 'sunil kumar', 'age': 23, 'Name': 'piyush', 'Age': 23}

`Problem-7` Write a python function that accepts a string as input and returns the word with most occurence.

```
Input:
hello how are you i am fine thank you
```

```
Output
you -> 2
```

In [27]:
def counts(s):
  dis = {}
  for i in s.split():
    if i in dis:
      dis[i] = dis[i] + 1
    else:
      dis[i] = 1
  maxi = max(dis.values())
  for i in dis:
    if(dis[i] == maxi):
      print(i,"->", maxi)
      break
s = "hello how are you i am fine thank you"
counts(s)

you -> 2

`Problem-8` Write a python function that receives a list of integers and prints out a histogram of bin size 10

```
Input:
[13,42,15,37,22,39,41,50]
```

```
Output:
{11-20:2,21-30:1,31-40:2,41-50:3}
```

In [33]:
import math
def histo(L):
  mini = math.floor((min(L)/10 ))* 10
  maxi = math.ceil((max(L)/10))* 10
  dic = {}
  for i in range(mini,maxi,10):
    count = 0
    for j in L:
      if(i + 1 <= j <= i + 10):
        count += 1
        dic[str(i+1) +"-"+ str(i+10) ] = count
  return dic
lst = [13,42,15,37,22,39,41,50]
histo(lst)

{'11-20': 2, '21-30': 1, '31-40': 2, '41-50': 3}

`Problem-9` Write a python function that accepts a list of 2D co-ordinates and a query point, and then finds the the co-ordinate which is closest in terms of distance from the query point.

```
List of Coordinates
[(1,1),(2,2),(3,3),(4,4)]
Query Point
(0,0)
```

```
Output
Nearest to (0,0) is (1,1)
```

In [68]:
def close(l,p):
  lst = []
  for i in l:
    distance = ((i[0] - p[0])**2 + (i[1] - p[1])**2)**0.5
    lst.append(distance)
  print(sorted(list(enumerate(lst)),key = lambda x:x[1]))
  return l[sorted(list(enumerate(lst)),key = lambda x:x[1])[0][0]]


lcord = [(1,1),(0,-1),(3,3),(4,4)]
qpoint = (0,0)
close(lcord,qpoint)

[(1, 1.0), (0, 1.4142135623730951), (2, 4.242640687119285), (3, 5.656854249492381)]

(0, -1)

`Problem-10`:Write a python program that receives a list of strings and performs bag of word operation on those strings

https://en.wikipedia.org/wiki/Bag-of-words_model

In [81]:

# Write code here
def bow(l):
  vocab = set()
  for i in l:
    vocab.update(i.split())
  result = []
  for i in l:
    result.append([])
    for j in vocab:
      result[-1].append(i.count(j))
  print(list(vocab))
  return result

lst = [ "cat mat cat",
       "rat hero mat",
        "mat cat rat hero"]
bow(lst)

['mat', 'rat', 'hero', 'cat']

[[1, 0, 0, 2], [1, 1, 1, 0], [1, 1, 1, 1]]

###`Problem 11:` Write a Python program to add three given lists using Python map and lambda.

In [1]:
l1 = [1,2,3]
l2 = [4,5,6]
l3 = [7,8,9]

list(map(lambda x,y,z: x+y+z, l1,l2,l3))

[12, 15, 18]

###`Problem-12:`Write a Python program to create a list containing the power of said number in bases raised to the corresponding number in the index using Python map.
`Input:`
```
list1 = [1,2,3,4,5,6]
```
`Output:`
```
[1,2,9,64,625,-]
```

In [5]:
list1 = [1,2,3,4,5,6]
list(map(lambda x,y:x**y ,list1,range(len(list1))))

[1, 2, 9, 64, 625, 7776]

###`Problem-13` Using filter() and list() functions and .lower() method filter all the vowels in a given string.

In [11]:
string = "i am A data scientist and i love programming"
vowel = "aeiou"
list(filter (lambda x: True if x.lower() in vowel else False, string))

['i', 'a', 'A', 'a', 'a', 'i', 'e', 'i', 'a', 'i', 'o', 'e', 'o', 'a', 'i']

`Problem-14`: Use reduce to convert a 2D list to 1D

In [14]:
import functools
lst = [[2,3,4],
       [5,6,7],
       [8,9,10]]
list(functools.reduce(lambda x,y: x+y ,lst))

[2, 3, 4, 5, 6, 7, 8, 9, 10]

`Problem 15`- A dictionary contains following information about 5 employees:
- First name
- Last name
- Age
- Grade(Skilled,Semi-skilled,Highly skilled)<br>
Write a program using map/filter/reduce to a list of employees(first name + last name) who are highly skilled

In [15]:
# Write code here
employees = [
    {
        'fname':'Nitish',
        'lname':'Singh',
        'age' : 33,
        'grade':'skilled'
    },
    {
        'fname':'Ankit',
        'lname':'Verma',
        'age' : 34,
        'grade':'semi-skilled'
    },
    {
        'fname':'Neha',
        'lname':'Singh',
        'age' : 35,
        'grade':'highly-skilled'
    },
    {
        'fname':'Anurag',
        'lname':'Kumar',
        'age' : 30,
        'grade':'skilled'
    },
    {
        'fname':'Abhinav',
        'lname':'Sharma',
        'age' : 37,
        'grade':'highly-skilled'
    }

]
print(employees)

[{'fname': 'Nitish', 'lname': 'Singh', 'age': 33, 'grade': 'skilled'}, {'fname': 'Ankit', 'lname': 'Verma', 'age': 34, 'grade': 'semi-skilled'}, {'fname': 'Neha', 'lname': 'Singh', 'age': 35, 'grade': 'highly-skilled'}, {'fname': 'Anurag', 'lname': 'Kumar', 'age': 30, 'grade': 'skilled'}, {'fname': 'Abhinav', 'lname': 'Sharma', 'age': 37, 'grade': 'highly-skilled'}]

In [18]:
list(map(lambda x: x["fname"] +" " + x["lname"],list(filter(lambda x: True if x["grade"] == "highly-skilled" else False,employees))))

['Neha Singh', 'Abhinav Sharma']