**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [2]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.

In [ ]:
a = np.nan * np.empty(10)
a[4] = 1
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
# a = int(input("Enter the rows your want : "))
# b = int(input("Enter the columns your want : "))
a, b = map(int,input("Enter the numbers : ").split())

r = np.random.random((a,b))
print(r)
print(f" Mean of the array is {np.mean(r)}")

Enter the numbers : 4 5
[[0.8907168  0.42230195 0.93030646 0.08352132 0.09053562]
 [0.58850649 0.99814039 0.44580298 0.3093059  0.55269101]
 [0.06556295 0.55387347 0.92333628 0.20692271 0.87499832]
 [0.17877132 0.5717175  0.28411153 0.96111766 0.68189845]]
 Mean of the array is 0.5307069563587603

###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [ ]:
def border(a,b):
  n = np.ones((a,b))
  n[1:a-1,1:b-1] = 0
  return n
border(4,5)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [ ]:
a = np.random.random(10)
print(a)

[0.98928376 0.30782288 0.33856637 0.57071651 0.78781627 0.04145769
 0.00418344 0.92794856 0.28783746 0.34356273]

In [ ]:
import numpy as np

vector = np.random.uniform(0, 1, 10)
print(vector)

[0.51379947 0.79031634 0.04032107 0.69763358 0.04286702 0.96303799
 0.1154126  0.83709481 0.25352614 0.84618542]

In [ ]:
a = np.random.uniform(0,1,10)
print(a)

[0.94312021 0.36090966 0.40285726 0.16819051 0.23579466 0.18517864
 0.51665771 0.95657331 0.17229793 0.04850278]

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
np.identity(5).reshape(3,4) #You can't do that.

ValueError: cannot reshape array of size 25 into shape (3,4)

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [5]:
a = np.zeros((5,5))
print(a)
b = np.arange(0,5)
print(b)
print(a+b)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0 1 2 3 4]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```

In [ ]:
a = np.random.randint(1,100,(10,2))
p = np.array([2,3])
print(a)
x = np.sqrt(np.sum((a * p)**2,axis = 1).astype(int))
x

[[55 24]
 [89 41]
 [26 92]
 [ 5 58]
 [49 95]
 [93 25]
 [79 74]
 [38 15]
 [72 43]
 [16 76]]

array([131.46862744, 216.3631207 , 280.8558349 , 174.28711943,
       301.37849956, 200.55173896, 272.48486196,  88.32326987,
       193.33132183, 230.2346629 ])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
n = np.zeros((6,7,8))
n
np.unravel_index(100,(6,7,8))

(1, 5, 4)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.

**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
a = input().strip().split()
n = np.array(a[::-1],dtype = np.float32)
print(n)

1 2 3 4 5 6 4 3 2 1
[1. 2. 3. 4. 6. 5. 4. 3. 2. 1.]

### `Q-10:` Elements count

Count the number of elements of a numpy array.

**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [ ]:
n = np.random.randint(1,100,(10,10))
# print(n)
# count = 0
# for i in np.nditer(n):
#   count += 1
# print(f"elements_count:{count}")
n.size

100

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function

**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
def softmax(num):
  if type(num) != np.ndarray:
    raise TypeError ("Enter only numpy array")
  s= sum(np.exp(num))
  return np.exp(num)/s
b = 1
n = np.array([33.17344305 ,45.61961654 ,82.05405781 ,80.9647098 , 68.82830233 ,91.5206427])
softmax(a)

array([[0.00669285, 0.00669285, 0.00669285, 0.00669285, 0.00669285],
       [0.99330715, 0.99330715, 0.99330715, 0.99330715, 0.99330715]])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.

**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
def vertical(*args):
  for i in args:
    if type(i) != np.ndarray:
      raise TypeError ("Enter only numpy array")
  return np.vstack((args))

a= np.array([[0 ,1 ,2, 3, 4],[5, 6, 7, 8, 9]])
v = 2
b= np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1 ,1]])
vertical(a,b)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.

**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
def date_array(start,end):
  if (type(start) != str and type(end) != str):
    raise TypeError ("Only enter dates")
  n = np.arange(start,end,dtype = "datetime64[D]")
  return n
date_array(start = '2020-11-25', end = '2020-11-30')

array(['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
       '2020-11-29'], dtype='datetime64[D]')

###`Q-14:` Subtract the mean of each row from a matrix.

In [8]:
n = np.random.randint(50,100,(5,5))
# print(n)
# m = np.linspace(1,100,20,dtype = int).reshape(5,4)
# print(m)
m = n.mean(axis = 1, keepdims= True)
print(m)
print(n-m)

[[72.6]
 [75.8]
 [82.4]
 [65.2]
 [69.4]]
[[-16.6  -4.6   6.4   8.4   6.4]
 [-17.8   9.2   0.2  10.2  -1.8]
 [  4.6  12.6  -1.4 -11.4  -4.4]
 [ -3.2  -5.2  -6.2  25.8 -11.2]
 [  5.6 -16.4  11.6  13.6 -14.4]]

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
a = np.arange(9).reshape(3,3)
a[:,[0,2,1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

###`Q-16:` Replace odd elements in arrays with -1.

In [9]:
a = np.arange(9).reshape(3,3)
print(a%2 != 0)
a[a%2 != 0] = -1
print(a)

[[False  True False]
 [ True False  True]
 [False  True False]]
[[ 0 -1  2]
 [-1  4 -1]
 [ 6 -1  8]]

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [ ]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
a[a<b] = b[a<b]
a

array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```

In [12]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
print(arr1)
arr2=np.random.randint(1,10000, (8,5))
print(arr2)

[[5805 3927 5379 3823 5479]
 [2299 8344 1393 3733 1277]
 [8865 4265 4763   66 6661]
 [2483 7052 4282 3331 1733]
 [3017 7402 7913 7523 9773]
 [6265  574   31  253 6197]
 [ 239 6014 3136 3437 7845]
 [8430 9710 2838 3915 3413]]
[[2706 1937 7080 3171 2234]
 [ 750  925 4922 7649 2713]
 [6646 6127 9655 9178 2742]
 [7525 8488 4944 4219 5822]
 [2504 8332 9480 8316  152]
 [4317 4603 5642 1592 3709]
 [9984 9660  774 8663 5360]
 [3662 8386 5957 5057 1244]]

In [ ]:
arr1[:,::2]

array([[7237, 3933, 2992],
       [4803, 9003, 9080],
       [ 917, 5349, 5258],
       [8410,  518, 4768],
       [5770,  842, 6914],
       [2161, 5766, 3141],
       [3425, 2584, 1430],
       [7657, 8182, 6473]])

In [ ]:
(arr1 - arr1.min())/(arr1.max() - arr1.min())

array([[0.78474655, 0.6827844 , 0.39885541, 0.52908199, 0.28895118],
       [0.50046718, 0.10418127, 0.99100677, 0.96180799, 1.        ],
       [0.04660126, 0.93459472, 0.56423733, 0.29759402, 0.55360897],
       [0.92174726, 0.79677645, 0.        , 0.94031768, 0.49637935],
       [0.61340808, 0.32772717, 0.03784163, 0.66479794, 0.74702172],
       [0.19189442, 0.88892782, 0.6129409 , 0.81955151, 0.30635366],
       [0.33952348, 0.95982247, 0.24129876, 0.53328662, 0.10651717],
       [0.83380051, 0.41637468, 0.89511796, 0.6491474 , 0.69551507]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [ ]:
def arg(arr,n):
  if (n>=len(arr)):
    raise TypeError ("n is bigger then length of array")
  arr.sort()
  return arr[-(n)]

arr = np.array([12,34,40,7,1,0])
n = 3
arg(arr,n)

12

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [18]:
n = np.array([1,2,3])
np.hstack([n.repeat(3),np.tile(n,3)])
np.tile(n,4)
n.repeat(3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])